trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  name: Default

steps:

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      arguments: --source https://api.nuget.org/v3/index.json

  - task: file-creator@5
    inputs:
      filepath: 'src/ITLab.Projects/appsettings.Secret.json'
      filecontent: '{}'
      endWithNewLine: true

  - task: file-creator@5
    inputs:
      filepath: 'src/ITLab.Projects.Database/appsettings.Secret.json'
      filecontent: '{}'
      endWithNewLine: true


  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: tests/**/*.fsproj
      arguments: --no-restore

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: 
      arguments: -o $(Build.ArtifactStagingDirectory) --no-restore
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: itlab-projects-build'
    inputs:
      ArtifactName: 'itlab-projects-build'

  - task: DeleteFiles@1
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '**'

  - task: CopyFiles@2
    displayName: 'copy deploy artifact'
    inputs:
      SourceFolder: 'deploy'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: itlab-projects-deploy'
    inputs:
      ArtifactName: 'itlab-projects-deploy'
